Sprint1
oier-elorrieta/E3_T3_PROG_GI pull request #1
Opened 2024-02-02 11:05 UTC by Unaiiss

Lehenengo sprint-a zuzentzeko

2024-02-05 10:24 UTC, oier-elorrieta requested changes
Lan txukuna egin duzue. Euskaratu erderaz dagoena eta erantzun egindako galdera, mesedez

2024-02-05 10:24 UTC, oier-elorrieta commented on 3Erronka/src/Modelo/Aretoa.java
> +	private Saioa[] saioak;
Ze erabilpen izango du saioak aretoan gordetzea?

2024-02-05 10:24 UTC, oier-elorrieta commented on 3Erronka/src/Modelo/AretoaTest.java
> +        assertTrue(aretoa1.equals(aretoa2)); // mismos valores, deberían ser iguales
Iruzkinak euskeraz jartzerik badago?

2024-02-06 09:58 UTC, oier-elorrieta requested changes
Oso lan ona egiten ari zarete. Pare bat detailetxo eta nik oneritzia emango dizuet.

Segi horrela!!!!

2024-02-06 09:58 UTC, oier-elorrieta commented on 3Erronka/src/Modelo/Aretoa.java
> +		this.data = data;
Kendu. Nahiz eta enuntziatuan jarri, egindako diseinuarekin ez dauka zentzurik. Ez data ez ordutegia.

2024-02-06 09:58 UTC, oier-elorrieta commented on 3Erronka/src/Modelo/Erosketa.java
> +	private String desk;
Nola erlazionatuko dituzue sarrerak eta erosketak?

2024-02-06 09:58 UTC, oier-elorrieta commented on 3Erronka/src/Modelo/Sarrera.java
> +		//seria prezio
Zertarako da iruzkin hori?

2024-02-07 08:38 UTC, oier-elorrieta approved these changes
Nire aldetik ontzat ematen dut. Daten asuntua begiratu ea erabaki onena hartu duzuen.

2024-02-07 08:38 UTC, oier-elorrieta commented on 3Erronka/src/Modelo/Saioa.java
> +	private Pelikula pelikula;
Data izango da String?

2024-02-07 12:19 UTC, OierZub approved these changes

2024-02-08 09:05 UTC, OierZub approved these changes

2024-02-08 09:13 UTC, merged